name: iOS Build & Sign (p12 in repo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Certificate
        run: |
          PASSWORD="czkeji"
          security create-keychain -p "" build.keychain
          security import cert.p12 -k ~/Library/Keychains/build.keychain -P "$PASSWORD" -T /usr/bin/codesign
          security default-keychain -s ~/Library/Keychains/build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: Build and Archive
        run: |
          xcodebuild clean archive \
            -workspace AssistantGPT.xcworkspace \
            -scheme AssistantGPT \
            -configuration Release \
            -archivePath $PWD/build/AssistantGPT.xcarchive \
            CODE_SIGN_STYLE=Manual

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/AssistantGPT.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AssistantGPT.ipa
          path: build/*.ipa
