name: iOS Build & Sign (Files in Repo)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Certificates and Profile
        run: |
          PASSWORD="czkeji"
          security create-keychain -p "" build.keychain
          security import cert.p12 -k ~/Library/Keychains/build.keychain -P "$PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install Dependencies
        run: |
          gem install cocoapods
          pod install || true

      - name: Build & Archive
        run: |
          xcodebuild clean archive \
            -workspace AssistantGPT.xcworkspace \
            -scheme AssistantGPT \
            -configuration Release \
            -archivePath $PWD/build/AssistantGPT.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="com.huaneng.lms2"

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/AssistantGPT.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AssistantGPT.ipa
          path: build/*.ipa
